// SYSTEM BOOT/RESET
export const IPCMAIN_SYSTEM_BOOT = 'IPCMAIN_SYSTEM_BOOT';
export const IPCMAIN_SYSTEM_RESET = 'IPCMAIN_SYSTEM_RESET';

// CONFIG MANAGER
export const IPCMAIN_REQUEST_SET_CONFIG = 'IPCMAIN_REQUEST_SET_CONFIG';
export const IPCMAIN_RESPONSE_SET_CONFIG = 'IPCMAIN_RESPONSE_SET_CONFIG';
export const IPCMAIN_REQUEST_GET_CONFIG = 'IPCMAIN_REQUEST_GET_CONFIG';
export const IPCMAIN_RESPONSE_GET_CONFIG = 'IPCMAIN_RESPONSE_GET_CONFIG';

// CONNECTION MANAGER
export const IPCMAIN_REQUEST_SAVE_DBCONNECTION = 'IPCMAIN_REQUEST_SAVE_DBCONNECTION';
export const IPCMAIN_RESPONSE_SAVE_DBCONNECTION = 'IPCMAIN_RESPONSE_SAVE_DBCONNECTION';
export const IPCMAIN_REQUEST_DELETE_DBCONNECTION = 'IPCMAIN_REQUEST_DELETE_DBCONNECTION';
export const IPCMAIN_RESPONSE_DELETE_DBCONNECTION = 'IPCMAIN_RESPONSE_DELETE_DBCONNECTION';
export const IPCMAIN_REQUEST_ENABLE_DBCONNECTION = 'IPCMAIN_REQUEST_ENABLE_DBCONNECTION';
export const IPCMAIN_REQUEST_TEST_CONNECTION = 'IPCMAIN_REQUEST_TEST_CONNECTION';
export const IPCMAIN_RESPONSE_TEST_CONNECTION = 'IPCMAIN_RESPONSE_TEST_CONNECTION';

// FONT MANAGER
export const IPCMAIN_REQUEST_EXECUTE_COMMAND = 'IPCMAIN_REQUEST_EXECUTE_COMMAND';
export const IPCMAIN_RESPONSE_EXECUTE_COMMAND = 'IPCMAIN_RESPONSE_EXECUTE_COMMAND';
export const IPCMAIN_REQUEST_FONT_ACTIVATION = 'IPCMAIN_REQUEST_FONT_ACTIVATION';
export const IPCMAIN_RESPONSE_FONT_ACTIVATION = 'IPCMAIN_RESPONSE_FONT_ACTIVATION';
export const IPCMAIN_REQUEST_FILES_SCAN = 'IPCMAIN_REQUEST_FILES_SCAN';
export const IPCMAIN_RESPONSE_FILES_SCAN = 'IPCMAIN_RESPONSE_FILES_SCAN';
export const IPCMAIN_REQUEST_FOLDERS_SCAN = 'IPCMAIN_REQUEST_FOLDERS_SCAN';
export const IPCMAIN_RESPONSE_FOLDERS_SCAN = 'IPCMAIN_RESPONSE_FOLDERS_SCAN';
export const IPCMAIN_REQUEST_SHOW_MESSAGE_BOX = 'IPCMAIN_REQUEST_SHOW_MESSAGE_BOX';
export const IPCMAIN_RESPONSE_SHOW_MESSAGE_BOX = 'IPCMAIN_RESPONSE_SHOW_MESSAGE_BOX';
export const IPCMAIN_REQUEST_SHOW_OPEN_DIALOG = 'IPCMAIN_REQUEST_SHOW_OPEN_DIALOG';
export const IPCMAIN_RESPONSE_SHOW_OPEN_DIALOG = 'IPCMAIN_RESPONSE_SHOW_OPEN_DIALOG';
export const IPCMAIN_REQUEST_OPEN_PATH = 'IPCMAIN_REQUEST_OPEN_PATH';
export const IPCMAIN_REQUEST_OPEN_EXTERNAL = 'IPCMAIN_REQUEST_OPEN_EXTERNAL';
export const IPCMAIN_REQUEST_SHOW_ITEM_FOLDER = 'IPCMAIN_REQUEST_SHOW_ITEM_FOLDER';
export const IPCMAIN_REQUEST_RELOAD_WINDOW = 'IPCMAIN_REQUEST_RELOAD_WINDOW';

// COLLECTION ENTITY
export const IPCMAIN_REQUEST_CREATE_COLLECTION = 'IPCMAIN_REQUEST_CREATE_COLLECTION';
export const IPCMAIN_REQUEST_DELETE_COLLECTION = 'IPCMAIN_REQUEST_DELETE_COLLECTION';
export const IPCMAIN_REQUEST_FETCH_COLLECTIONS = 'IPCMAIN_REQUEST_FETCH_COLLECTIONS';
export const IPCMAIN_REQUEST_UPDATE_COLLECTION = 'IPCMAIN_REQUEST_UPDATE_COLLECTION';
export const IPCMAIN_RESPONSE_UPDATE_COLLECTION = 'IPCMAIN_RESPONSE_UPDATE_COLLECTION';
export const IPCMAIN_REQUEST_RESET_ENABLED = 'IPCMAIN_REQUEST_RESET_ENABLED';
export const IPCMAIN_RESPONSE_RESET_ENABLED = 'IPCMAIN_RESPONSE_RESET_ENABLED';

// STORE ENTITY
export const IPCMAIN_REQUEST_STORE_QUERY = 'IPCMAIN_REQUEST_STORE_QUERY';
export const IPCMAIN_RESPONSE_STORE_QUERY = 'IPCMAIN_RESPONSE_STORE_QUERY';
export const IPCMAIN_REQUEST_FONT_INFORMATION = 'IPCMAIN_REQUEST_FONT_INFORMATION';
export const IPCMAIN_RESPONSE_FONT_INFORMATION = 'IPCMAIN_RESPONSE_FONT_INFORMATION';
export const IPCMAIN_REQUEST_UPDATE_STORE = 'IPCMAIN_REQUEST_UPDATE_STORE';
export const IPCMAIN_REQUEST_UPDATE_COUNT = 'IPCMAIN_REQUEST_UPDATE_COUNT';
export const IPCMAIN_REQUEST_UPDATE_COUNTS = 'IPCMAIN_REQUEST_UPDATE_COUNTS';
export const IPCMAIN_REQUEST_SYSTEM_FONTS = 'IPCMAIN_REQUEST_SYSTEM_FONTS';
export const IPCMAIN_RESPONSE_SYSTEM_FONTS = 'IPCMAIN_RESPONSE_SYSTEM_FONTS';
export const IPCMAIN_REQUEST_ACTIVATED_FONTS = 'IPCMAIN_REQUEST_ACTIVATED_FONTS';
export const IPCMAIN_RESPONSE_ACTIVATED_FONTS = 'IPCMAIN_RESPONSE_ACTIVATED_FONTS';
export const IPCMAIN_REQUEST_RESET_FAVORITES = 'IPCMAIN_REQUEST_RESET_FAVORITES';
export const IPCMAIN_RESPONSE_RESET_FAVORITES = 'IPCMAIN_RESPONSE_RESET_FAVORITES';
export const IPCMAIN_REQUEST_RESET_ACTIVATED = 'IPCMAIN_REQUEST_RESET_ACTIVATED';
export const IPCMAIN_RESPONSE_RESET_ACTIVATED = 'IPCMAIN_RESPONSE_RESET_ACTIVATED';
export const IPCMAIN_REQUEST_SYSTEM_STATS = 'IPCMAIN_REQUEST_SYSTEM_STATS';
export const IPCMAIN_RESPONSE_SYSTEM_STATS = 'IPCMAIN_RESPONSE_SYSTEM_STATS';

// LOGGER ENTITY
export const IPCMAIN_REQUEST_LOGGER_CREATE = 'IPCMAIN_REQUEST_LOGGER_CREATE';
export const IPCMAIN_REQUEST_LOGGER_DELETE = 'IPCMAIN_REQUEST_LOGGER_DELETE';
export const IPCMAIN_REQUEST_LOGGER_QUERY = 'IPCMAIN_REQUEST_LOGGER_QUERY';
export const IPCMAIN_RESPONSE_LOGGER_QUERY = 'IPCMAIN_RESPONSE_LOGGER_QUERY';
export const IPCMAIN_REQUEST_LOGGER_DELETE_ITEM = 'IPCMAIN_REQUEST_LOGGER_DELETE_ITEM';
export const IPCMAIN_RESPONSE_LOGGER_DELETE_ITEM = 'IPCMAIN_RESPONSE_LOGGER_DELETE_ITEM';
export const IPCMAIN_REQUEST_LOGGER_TRUNCATE = 'IPCMAIN_REQUEST_LOGGER_TRUNCATE';
export const IPCMAIN_RESPONSE_LOGGER_TRUNCATE = 'IPCMAIN_RESPONSE_LOGGER_TRUNCATE';
