"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPCMAIN_REQUEST_STORE_FETCH_ROW = exports.IPCMAIN_RESPONSE_STORE_FETCH_ALL = exports.IPCMAIN_REQUEST_STORE_FETCH_ALL = exports.IPCMAIN_RESPONSE_RESET_ENABLED = exports.IPCMAIN_REQUEST_RESET_ENABLED = exports.IPCMAIN_RESPONSE_UPDATE_COLLECTION = exports.IPCMAIN_REQUEST_UPDATE_COLLECTION = exports.IPCMAIN_REQUEST_FETCH_COLLECTIONS = exports.IPCMAIN_REQUEST_DELETE_COLLECTION = exports.IPCMAIN_REQUEST_CREATE_COLLECTION = exports.IPCMAIN_REQUEST_BEEP = exports.IPCMAIN_REQUEST_QUIT = exports.IPCMAIN_REQUEST_EXIT = exports.IPCMAIN_REQUEST_RELOAD_WINDOW = exports.IPCMAIN_REQUEST_SHOW_ITEM_FOLDER = exports.IPCMAIN_REQUEST_OPEN_EXTERNAL = exports.IPCMAIN_REQUEST_OPEN_PATH = exports.IPCMAIN_RESPONSE_SHOW_OPEN_DIALOG = exports.IPCMAIN_REQUEST_SHOW_OPEN_DIALOG = exports.IPCMAIN_RESPONSE_SHOW_MESSAGE_BOX = exports.IPCMAIN_REQUEST_SHOW_MESSAGE_BOX = exports.IPCMAIN_RESPONSE_FOLDERS_SCAN = exports.IPCMAIN_REQUEST_FOLDERS_SCAN = exports.IPCMAIN_RESPONSE_FILES_SCAN = exports.IPCMAIN_REQUEST_FILES_SCAN = exports.IPCMAIN_RESPONSE_FONT_ACTIVATION = exports.IPCMAIN_REQUEST_FONT_ACTIVATION = exports.IPCMAIN_RESPONSE_EXECUTE_COMMAND = exports.IPCMAIN_REQUEST_EXECUTE_COMMAND = exports.IPCMAIN_RESPONSE_SYSTEM_AUTH = exports.IPCMAIN_REQUEST_SYSTEM_AUTH = exports.IPCMAIN_RESPONSE_TRUNCATE_DATABASE = exports.IPCMAIN_REQUEST_TRUNCATE_DATABASE = exports.IPCMAIN_RESPONSE_DROP_DATABASE = exports.IPCMAIN_REQUEST_DROP_DATABASE = exports.IPCMAIN_RESPONSE_TEST_CONNECTION = exports.IPCMAIN_REQUEST_TEST_CONNECTION = exports.IPCMAIN_REQUEST_ENABLE_DBCONNECTION = exports.IPCMAIN_RESPONSE_DELETE_DBCONNECTION = exports.IPCMAIN_REQUEST_DELETE_DBCONNECTION = exports.IPCMAIN_RESPONSE_SAVE_DBCONNECTION = exports.IPCMAIN_REQUEST_SAVE_DBCONNECTION = exports.IPCMAIN_RESPONSE_CLEAR_STORE = exports.IPCMAIN_REQUEST_CLEAR_STORE = exports.IPCMAIN_RESPONSE_GET_CONFIG = exports.IPCMAIN_REQUEST_GET_CONFIG = exports.IPCMAIN_RESPONSE_SET_CONFIG = exports.IPCMAIN_REQUEST_SET_CONFIG = exports.IPCMAIN_SYSTEM_RESET = exports.IPCMAIN_SYSTEM_BOOT = void 0;
exports.IPCMAIN_RESPONSE_LOGGER_TRUNCATE = exports.IPCMAIN_REQUEST_LOGGER_TRUNCATE = exports.IPCMAIN_RESPONSE_LOGGER_DELETE_ITEM = exports.IPCMAIN_REQUEST_LOGGER_DELETE_ITEM = exports.IPCMAIN_RESPONSE_LOGGER_QUERY = exports.IPCMAIN_REQUEST_LOGGER_QUERY = exports.IPCMAIN_REQUEST_LOGGER_DELETE = exports.IPCMAIN_REQUEST_LOGGER_CREATE = exports.IPCMAIN_RESPONSE_SYSTEM_STATS = exports.IPCMAIN_REQUEST_SYSTEM_STATS = exports.IPCMAIN_RESPONSE_RESET_FAVORITES = exports.IPCMAIN_REQUEST_RESET_FAVORITES = exports.IPCMAIN_RESPONSE_SYNC_ACTIVATED = exports.IPCMAIN_REQUEST_SYNC_ACTIVATED = exports.IPCMAIN_RESPONSE_SYNC_SYSTEM = exports.IPCMAIN_REQUEST_SYNC_SYSTEM = exports.IPCMAIN_REQUEST_UPDATE_COUNTS = exports.IPCMAIN_REQUEST_UPDATE_COUNT = exports.IPCMAIN_RESPONSE_STORE_UPDATE = exports.IPCMAIN_REQUEST_STORE_UPDATE = exports.IPCMAIN_RESPONSE_STORE_FETCH_ROW = void 0;
// SYSTEM BOOT/RESET
exports.IPCMAIN_SYSTEM_BOOT = 'IPCMAIN_SYSTEM_BOOT';
exports.IPCMAIN_SYSTEM_RESET = 'IPCMAIN_SYSTEM_RESET';
// CONFIG MANAGER
exports.IPCMAIN_REQUEST_SET_CONFIG = 'IPCMAIN_REQUEST_SET_CONFIG';
exports.IPCMAIN_RESPONSE_SET_CONFIG = 'IPCMAIN_RESPONSE_SET_CONFIG';
exports.IPCMAIN_REQUEST_GET_CONFIG = 'IPCMAIN_REQUEST_GET_CONFIG';
exports.IPCMAIN_RESPONSE_GET_CONFIG = 'IPCMAIN_RESPONSE_GET_CONFIG';
exports.IPCMAIN_REQUEST_CLEAR_STORE = 'IPCMAIN_REQUEST_CLEAR_STORE';
exports.IPCMAIN_RESPONSE_CLEAR_STORE = 'IPCMAIN_RESPONSE_CLEAR_STORE';
// CONNECTION MANAGER
exports.IPCMAIN_REQUEST_SAVE_DBCONNECTION = 'IPCMAIN_REQUEST_SAVE_DBCONNECTION';
exports.IPCMAIN_RESPONSE_SAVE_DBCONNECTION = 'IPCMAIN_RESPONSE_SAVE_DBCONNECTION';
exports.IPCMAIN_REQUEST_DELETE_DBCONNECTION = 'IPCMAIN_REQUEST_DELETE_DBCONNECTION';
exports.IPCMAIN_RESPONSE_DELETE_DBCONNECTION = 'IPCMAIN_RESPONSE_DELETE_DBCONNECTION';
exports.IPCMAIN_REQUEST_ENABLE_DBCONNECTION = 'IPCMAIN_REQUEST_ENABLE_DBCONNECTION';
exports.IPCMAIN_REQUEST_TEST_CONNECTION = 'IPCMAIN_REQUEST_TEST_CONNECTION';
exports.IPCMAIN_RESPONSE_TEST_CONNECTION = 'IPCMAIN_RESPONSE_TEST_CONNECTION';
exports.IPCMAIN_REQUEST_DROP_DATABASE = 'IPCMAIN_REQUEST_DROP_DATABASE';
exports.IPCMAIN_RESPONSE_DROP_DATABASE = 'IPCMAIN_RESPONSE_DROP_DATABASE';
exports.IPCMAIN_REQUEST_TRUNCATE_DATABASE = 'IPCMAIN_REQUEST_TRUNCATE_DATABASE';
exports.IPCMAIN_RESPONSE_TRUNCATE_DATABASE = 'IPCMAIN_RESPONSE_TRUNCATE_DATABASE';
// FONT MANAGER
exports.IPCMAIN_REQUEST_SYSTEM_AUTH = 'IPCMAIN_REQUEST_SYSTEM_AUTH';
exports.IPCMAIN_RESPONSE_SYSTEM_AUTH = 'IPCMAIN_RESPONSE_SYSTEM_AUTH';
exports.IPCMAIN_REQUEST_EXECUTE_COMMAND = 'IPCMAIN_REQUEST_EXECUTE_COMMAND';
exports.IPCMAIN_RESPONSE_EXECUTE_COMMAND = 'IPCMAIN_RESPONSE_EXECUTE_COMMAND';
exports.IPCMAIN_REQUEST_FONT_ACTIVATION = 'IPCMAIN_REQUEST_FONT_ACTIVATION';
exports.IPCMAIN_RESPONSE_FONT_ACTIVATION = 'IPCMAIN_RESPONSE_FONT_ACTIVATION';
exports.IPCMAIN_REQUEST_FILES_SCAN = 'IPCMAIN_REQUEST_FILES_SCAN';
exports.IPCMAIN_RESPONSE_FILES_SCAN = 'IPCMAIN_RESPONSE_FILES_SCAN';
exports.IPCMAIN_REQUEST_FOLDERS_SCAN = 'IPCMAIN_REQUEST_FOLDERS_SCAN';
exports.IPCMAIN_RESPONSE_FOLDERS_SCAN = 'IPCMAIN_RESPONSE_FOLDERS_SCAN';
exports.IPCMAIN_REQUEST_SHOW_MESSAGE_BOX = 'IPCMAIN_REQUEST_SHOW_MESSAGE_BOX';
exports.IPCMAIN_RESPONSE_SHOW_MESSAGE_BOX = 'IPCMAIN_RESPONSE_SHOW_MESSAGE_BOX';
exports.IPCMAIN_REQUEST_SHOW_OPEN_DIALOG = 'IPCMAIN_REQUEST_SHOW_OPEN_DIALOG';
exports.IPCMAIN_RESPONSE_SHOW_OPEN_DIALOG = 'IPCMAIN_RESPONSE_SHOW_OPEN_DIALOG';
exports.IPCMAIN_REQUEST_OPEN_PATH = 'IPCMAIN_REQUEST_OPEN_PATH';
exports.IPCMAIN_REQUEST_OPEN_EXTERNAL = 'IPCMAIN_REQUEST_OPEN_EXTERNAL';
exports.IPCMAIN_REQUEST_SHOW_ITEM_FOLDER = 'IPCMAIN_REQUEST_SHOW_ITEM_FOLDER';
exports.IPCMAIN_REQUEST_RELOAD_WINDOW = 'IPCMAIN_REQUEST_RELOAD_WINDOW';
exports.IPCMAIN_REQUEST_EXIT = 'IPCMAIN_REQUEST_EXIT';
exports.IPCMAIN_REQUEST_QUIT = 'IPCMAIN_REQUEST_QUIT';
exports.IPCMAIN_REQUEST_BEEP = 'IPCMAIN_REQUEST_BEEP';
// COLLECTION
exports.IPCMAIN_REQUEST_CREATE_COLLECTION = 'IPCMAIN_REQUEST_CREATE_COLLECTION';
exports.IPCMAIN_REQUEST_DELETE_COLLECTION = 'IPCMAIN_REQUEST_DELETE_COLLECTION';
exports.IPCMAIN_REQUEST_FETCH_COLLECTIONS = 'IPCMAIN_REQUEST_FETCH_COLLECTIONS';
exports.IPCMAIN_REQUEST_UPDATE_COLLECTION = 'IPCMAIN_REQUEST_UPDATE_COLLECTION';
exports.IPCMAIN_RESPONSE_UPDATE_COLLECTION = 'IPCMAIN_RESPONSE_UPDATE_COLLECTION';
exports.IPCMAIN_REQUEST_RESET_ENABLED = 'IPCMAIN_REQUEST_RESET_ENABLED';
exports.IPCMAIN_RESPONSE_RESET_ENABLED = 'IPCMAIN_RESPONSE_RESET_ENABLED';
// STORE
exports.IPCMAIN_REQUEST_STORE_FETCH_ALL = 'IPCMAIN_REQUEST_STORE_FETCH_ALL';
exports.IPCMAIN_RESPONSE_STORE_FETCH_ALL = 'IPCMAIN_RESPONSE_STORE_FETCH_ALL';
exports.IPCMAIN_REQUEST_STORE_FETCH_ROW = 'IPCMAIN_REQUEST_STORE_FETCH_ROW';
exports.IPCMAIN_RESPONSE_STORE_FETCH_ROW = 'IPCMAIN_RESPONSE_STORE_FETCH_ROW';
exports.IPCMAIN_REQUEST_STORE_UPDATE = 'IPCMAIN_REQUEST_STORE_UPDATE';
exports.IPCMAIN_RESPONSE_STORE_UPDATE = 'IPCMAIN_RESPONSE_STORE_UPDATE';
exports.IPCMAIN_REQUEST_UPDATE_COUNT = 'IPCMAIN_REQUEST_UPDATE_COUNT';
exports.IPCMAIN_REQUEST_UPDATE_COUNTS = 'IPCMAIN_REQUEST_UPDATE_COUNTS';
exports.IPCMAIN_REQUEST_SYNC_SYSTEM = 'IPCMAIN_REQUEST_SYNC_SYSTEM';
exports.IPCMAIN_RESPONSE_SYNC_SYSTEM = 'IPCMAIN_RESPONSE_SYNC_SYSTEM';
exports.IPCMAIN_REQUEST_SYNC_ACTIVATED = 'IPCMAIN_REQUEST_SYNC_ACTIVATED';
exports.IPCMAIN_RESPONSE_SYNC_ACTIVATED = 'IPCMAIN_RESPONSE_SYNC_ACTIVATED';
exports.IPCMAIN_REQUEST_RESET_FAVORITES = 'IPCMAIN_REQUEST_RESET_FAVORITES';
exports.IPCMAIN_RESPONSE_RESET_FAVORITES = 'IPCMAIN_RESPONSE_RESET_FAVORITES';
exports.IPCMAIN_REQUEST_SYSTEM_STATS = 'IPCMAIN_REQUEST_SYSTEM_STATS';
exports.IPCMAIN_RESPONSE_SYSTEM_STATS = 'IPCMAIN_RESPONSE_SYSTEM_STATS';
// LOGGER
exports.IPCMAIN_REQUEST_LOGGER_CREATE = 'IPCMAIN_REQUEST_LOGGER_CREATE';
exports.IPCMAIN_REQUEST_LOGGER_DELETE = 'IPCMAIN_REQUEST_LOGGER_DELETE';
exports.IPCMAIN_REQUEST_LOGGER_QUERY = 'IPCMAIN_REQUEST_LOGGER_QUERY';
exports.IPCMAIN_RESPONSE_LOGGER_QUERY = 'IPCMAIN_RESPONSE_LOGGER_QUERY';
exports.IPCMAIN_REQUEST_LOGGER_DELETE_ITEM = 'IPCMAIN_REQUEST_LOGGER_DELETE_ITEM';
exports.IPCMAIN_RESPONSE_LOGGER_DELETE_ITEM = 'IPCMAIN_RESPONSE_LOGGER_DELETE_ITEM';
exports.IPCMAIN_REQUEST_LOGGER_TRUNCATE = 'IPCMAIN_REQUEST_LOGGER_TRUNCATE';
exports.IPCMAIN_RESPONSE_LOGGER_TRUNCATE = 'IPCMAIN_RESPONSE_LOGGER_TRUNCATE';
//# sourceMappingURL=channel.js.map