export enum ChannelType {
  IPC_REQUEST_SYSTEM_BOOT = 'IPC_REQUEST_SYSTEM_BOOT',
  IPC_RESPONSE_SYSTEM_BOOT = 'IPC_RESPONSE_SYSTEM_BOOT',

  IPC_SYSTEM_REBOOT = 'IPC_SYSTEM_REBOOT',

  IPC_SET_CONFIG = 'IPC_SET_CONFIG',
  IPC_GET_CONFIG = 'IPC_GET_CONFIG',
  IPC_ZAP_CONFIG = 'IPC_ZAP_CONFIG',

  IPC_DBCONNECTION_CREATE = 'IPC_DBCONNECTION_CREATE',
  IPC_DBCONNECTION_ENABLE = 'IPC_DBCONNECTION_ENABLE',
  IPC_DBCONNECTION_DELETE = 'IPC_DBCONNECTION_DELETE',
  IPC_DBCONNECTION_TEST = 'IPC_DBCONNECTION_TEST',
  IPC_DATABASE_DROP = 'IPC_DATABASE_DROP',

  IPC_EXEC_CMD = 'IPC_EXEC_CMD',
  IPC_AUTH_USER = 'IPC_AUTH_USER',
  IPC_SCAN_FILES = 'IPC_SCAN_FILES',
  IPC_SCAN_FOLDERS = 'IPC_SCAN_FOLDERS',
  IPC_FETCH_NEWS = 'IPC_FETCH_NEWS',

  IPC_SHOW_MESSAGE_BOX = 'IPC_SHOW_MESSAGE_BOX',
  IPC_SHOW_OPEN_DIALOG = 'IPC_SHOW_OPEN_DIALOG',
  IPC_OPEN_PATH = 'IPC_OPEN_PATH',
  IPC_OPEN_EXTERNAL = 'IPC_OPEN_EXTERNAL',
  IPC_OPEN_FOLDER = 'IPC_OPEN_FOLDER',
  IPC_RELOAD_WINDOW = 'IPC_RELOAD_WINDOW',
  IPC_EXIT = 'IPC_EXIT',
  IPC_QUIT = 'IPC_QUIT',
  IPC_BEEP = 'IPC_BEEP',

  IPC_COLLECTION_FIND = 'IPC_COLLECTION_FIND',
  IPC_COLLECTION_FIND_ONE = 'IPC_COLLECTION_FIND_ONE',
  IPC_COLLECTION_FIND_ONE_BY = 'IPC_COLLECTION_FIND_ONE_BY',
  IPC_COLLECTION_FETCH = 'IPC_COLLECTION_FETCH',
  IPC_COLLECTION_CREATE = 'IPC_COLLECTION_CREATE',
  IPC_COLLECTION_UPDATE = 'IPC_COLLECTION_UPDATE',
  IPC_COLLECTION_UPDATE_IDS = 'IPC_COLLECTION_UPDATE_IDS',
  IPC_COLLECTION_DELETE = 'IPC_COLLECTION_DELETE',
  IPC_COLLECTION_ENABLE = 'IPC_COLLECTION_ENABLE',
  IPC_COLLECTION_UPDATE_COUNT = 'IPC_COLLECTION_UPDATE_COUNT',
  IPC_COLLECTION_UPDATE_COUNTS = 'IPC_COLLECTION_UPDATE_COUNTS',
  IPC_COLLECTION_MOVE = 'IPC_COLLECTION_MOVE',

  IPC_STORE_FIND = 'IPC_STORE_FIND',
  IPC_STORE_FIND_ONE = 'IPC_STORE_FIND_ONE',
  IPC_STORE_FIND_ONE_BY = 'IPC_STORE_FIND_ONE_BY',
  IPC_STORE_FETCH = 'IPC_STORE_FETCH',
  IPC_STORE_SEARCH = 'IPC_STORE_SEARCH',
  IPC_STORE_UPDATE = 'IPC_STORE_UPDATE',
  IPC_STORE_SYNC_SYSTEM = 'IPC_STORE_SYNC_SYSTEM',
  IPC_STORE_RESET_FAVORITES = 'IPC_STORE_RESET_FAVORITES',
  IPC_STORE_SYSTEM_STATS = 'IPC_STORE_SYSTEM_STATS',
  IPC_FONT_METRICS = 'IPC_FONT_METRICS',
  IPC_FONT_GLYPHS = 'IPC_FONT_GLYPHS',

  IPC_LOGGER_FIND = 'IPC_LOGGER_FIND',
  IPC_LOGGER_FIND_ONE = 'IPC_LOGGER_FIND_ONE',
  IPC_LOGGER_FIND_ONE_BY = 'IPC_LOGGER_FIND_ONE_BY',
  IPC_LOGGER_CREATE = 'IPC_LOGGER_CREATE',
  IPC_LOGGER_DELETE = 'IPC_LOGGER_DELETE',
  IPC_LOGGER_QUERY = 'IPC_LOGGER_QUERY',
  IPC_LOGGER_TRUNCATE = 'IPC_LOGGER_TRUNCATE',

  IPC_SMART_COLLECTION_FIND = 'IPC_SMART_COLLECTION_FIND',
  IPC_SMART_COLLECTION_CREATE = 'IPC_SMART_COLLECTION_CREATE',
  IPC_SMART_COLLECTION_UPDATE = 'IPC_SMART_COLLECTION_UPDATE',
  IPC_SMART_COLLECTION_DELETE = 'IPC_SMART_COLLECTION_DELETE',
  IPC_SMART_COLLECTION_EVALUATE = 'IPC_SMART_COLLECTION_EVALUATE',
  IPC_SMART_COLLECTION_PREVIEW = 'IPC_SMART_COLLECTION_PREVIEW',

  IPC_TOGGLE_PANEL = 'IPC_TOGGLE_PANEL',

  // Native Theme
  IPC_GET_NATIVE_THEME = 'IPC_GET_NATIVE_THEME',
  IPC_NATIVE_THEME_CHANGED = 'IPC_NATIVE_THEME_CHANGED',

  // Safe Storage
  IPC_SAFE_STORE = 'IPC_SAFE_STORE',
  IPC_SAFE_RETRIEVE = 'IPC_SAFE_RETRIEVE',

  // Session
  IPC_CLEAR_CACHE = 'IPC_CLEAR_CACHE',

  // Power Monitor
  IPC_POWER_SUSPEND = 'IPC_POWER_SUSPEND',
  IPC_POWER_RESUME = 'IPC_POWER_RESUME',
  IPC_POWER_SHUTDOWN = 'IPC_POWER_SHUTDOWN',
  IPC_POWER_LOCK_SCREEN = 'IPC_POWER_LOCK_SCREEN',

  // System Preferences
  IPC_GET_SYSTEM_PREFERENCES = 'IPC_GET_SYSTEM_PREFERENCES',

  // Scan Progress (MessageChannelMain)
  IPC_SCAN_PROGRESS_PORT = 'IPC_SCAN_PROGRESS_PORT',
}
