"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelType = void 0;
var ChannelType;
(function (ChannelType) {
    // SYSTEM BOOT/RESET
    ChannelType["IPCMAIN_SYSTEM_BOOT"] = "IPCMAIN_SYSTEM_BOOT";
    ChannelType["IPCMAIN_REQUEST_SYSTEM_BOOT"] = "IPCMAIN_REQUEST_SYSTEM_BOOT";
    ChannelType["IPCMAIN_RESPONSE_SYSTEM_BOOT"] = "IPCMAIN_RESPONSE_SYSTEM_BOOT";
    ChannelType["IPCMAIN_REQUEST_SYSTEM_RESET"] = "IPCMAIN_REQUEST_SYSTEM_RESET";
    ChannelType["IPCMAIN_RESPONSE_SYSTEM_RESET"] = "IPCMAIN_RESPONSE_SYSTEM_RESET";
    // CONFIG MANAGER
    ChannelType["IPCMAIN_REQUEST_SET_CONFIG"] = "IPCMAIN_REQUEST_SET_CONFIG";
    ChannelType["IPCMAIN_RESPONSE_SET_CONFIG"] = "IPCMAIN_RESPONSE_SET_CONFIG";
    ChannelType["IPCMAIN_REQUEST_GET_CONFIG"] = "IPCMAIN_REQUEST_GET_CONFIG";
    ChannelType["IPCMAIN_RESPONSE_GET_CONFIG"] = "IPCMAIN_RESPONSE_GET_CONFIG";
    ChannelType["IPCMAIN_REQUEST_CLEAR_STORE"] = "IPCMAIN_REQUEST_CLEAR_STORE";
    ChannelType["IPCMAIN_RESPONSE_CLEAR_STORE"] = "IPCMAIN_RESPONSE_CLEAR_STORE";
    // CONNECTION MANAGER
    ChannelType["IPCMAIN_REQUEST_SAVE_DBCONNECTION"] = "IPCMAIN_REQUEST_SAVE_DBCONNECTION";
    ChannelType["IPCMAIN_RESPONSE_SAVE_DBCONNECTION"] = "IPCMAIN_RESPONSE_SAVE_DBCONNECTION";
    ChannelType["IPCMAIN_REQUEST_DELETE_DBCONNECTION"] = "IPCMAIN_REQUEST_DELETE_DBCONNECTION";
    ChannelType["IPCMAIN_RESPONSE_DELETE_DBCONNECTION"] = "IPCMAIN_RESPONSE_DELETE_DBCONNECTION";
    ChannelType["IPCMAIN_REQUEST_ENABLE_DBCONNECTION"] = "IPCMAIN_REQUEST_ENABLE_DBCONNECTION";
    ChannelType["IPCMAIN_RESPONSE_ENABLE_DBCONNECTION"] = "IPCMAIN_RESPONSE_ENABLE_DBCONNECTION";
    ChannelType["IPCMAIN_REQUEST_TEST_CONNECTION"] = "IPCMAIN_REQUEST_TEST_CONNECTION";
    ChannelType["IPCMAIN_RESPONSE_TEST_CONNECTION"] = "IPCMAIN_RESPONSE_TEST_CONNECTION";
    ChannelType["IPCMAIN_REQUEST_DROP_DATABASE"] = "IPCMAIN_REQUEST_DROP_DATABASE";
    ChannelType["IPCMAIN_RESPONSE_DROP_DATABASE"] = "IPCMAIN_RESPONSE_DROP_DATABASE";
    // FONT MANAGER
    ChannelType["IPCMAIN_REQUEST_AUTH_USER"] = "IPCMAIN_REQUEST_AUTH_USER";
    ChannelType["IPCMAIN_RESPONSE_AUTH_USER"] = "IPCMAIN_RESPONSE_AUTH_USER";
    ChannelType["IPCMAIN_REQUEST_FETCH_NEWS"] = "IPCMAIN_REQUEST_FETCH_NEWS";
    ChannelType["IPCMAIN_RESPONSE_FETCH_NEWS"] = "IPCMAIN_RESPONSE_FETCH_NEWS";
    ChannelType["IPCMAIN_REQUEST_NEWS_CONTENT"] = "IPCMAIN_REQUEST_NEWS_CONTENT";
    ChannelType["IPCMAIN_RESPONSE_NEWS_CONTENT"] = "IPCMAIN_RESPONSE_NEWS_CONTENT";
    ChannelType["IPCMAIN_REQUEST_EXECUTE_COMMAND"] = "IPCMAIN_REQUEST_EXECUTE_COMMAND";
    ChannelType["IPCMAIN_RESPONSE_EXECUTE_COMMAND"] = "IPCMAIN_RESPONSE_EXECUTE_COMMAND";
    ChannelType["IPCMAIN_REQUEST_FONT_ACTIVATION"] = "IPCMAIN_REQUEST_FONT_ACTIVATION";
    ChannelType["IPCMAIN_RESPONSE_FONT_ACTIVATION"] = "IPCMAIN_RESPONSE_FONT_ACTIVATION";
    ChannelType["IPCMAIN_REQUEST_FILES_SCAN"] = "IPCMAIN_REQUEST_FILES_SCAN";
    ChannelType["IPCMAIN_RESPONSE_FILES_SCAN"] = "IPCMAIN_RESPONSE_FILES_SCAN";
    ChannelType["IPCMAIN_REQUEST_FOLDERS_SCAN"] = "IPCMAIN_REQUEST_FOLDERS_SCAN";
    ChannelType["IPCMAIN_RESPONSE_FOLDERS_SCAN"] = "IPCMAIN_RESPONSE_FOLDERS_SCAN";
    ChannelType["IPCMAIN_REQUEST_MESSAGE_BOX"] = "IPCMAIN_REQUEST_MESSAGE_BOX";
    ChannelType["IPCMAIN_RESPONSE_MESSAGE_BOX"] = "IPCMAIN_RESPONSE_MESSAGE_BOX";
    ChannelType["IPCMAIN_REQUEST_OPEN_DIALOG"] = "IPCMAIN_REQUEST_OPEN_DIALOG";
    ChannelType["IPCMAIN_RESPONSE_OPEN_DIALOG"] = "IPCMAIN_RESPONSE_OPEN_DIALOG";
    ChannelType["IPCMAIN_REQUEST_OPEN_PATH"] = "IPCMAIN_REQUEST_OPEN_PATH";
    ChannelType["IPCMAIN_REQUEST_OPEN_EXTERNAL"] = "IPCMAIN_REQUEST_OPEN_EXTERNAL";
    ChannelType["IPCMAIN_REQUEST_OPEN_FOLDER"] = "IPCMAIN_REQUEST_OPEN_FOLDER";
    ChannelType["IPCMAIN_REQUEST_RELOAD_WINDOW"] = "IPCMAIN_REQUEST_RELOAD_WINDOW";
    ChannelType["IPCMAIN_REQUEST_EXIT"] = "IPCMAIN_REQUEST_EXIT";
    ChannelType["IPCMAIN_REQUEST_QUIT"] = "IPCMAIN_REQUEST_QUIT";
    ChannelType["IPCMAIN_REQUEST_BEEP"] = "IPCMAIN_REQUEST_BEEP";
    // COLLECTION
    ChannelType["IPCMAIN_REQUEST_CREATE_COLLECTION"] = "IPCMAIN_REQUEST_CREATE_COLLECTION";
    ChannelType["IPCMAIN_RESPONSE_CREATE_COLLECTION"] = "IPCMAIN_RESPONSE_CREATE_COLLECTION";
    ChannelType["IPCMAIN_REQUEST_DELETE_COLLECTION"] = "IPCMAIN_REQUEST_DELETE_COLLECTION";
    ChannelType["IPCMAIN_RESPONSE_DELETE_COLLECTION"] = "IPCMAIN_RESPONSE_DELETE_COLLECTION";
    ChannelType["IPCMAIN_REQUEST_FETCH_COLLECTIONS"] = "IPCMAIN_REQUEST_FETCH_COLLECTIONS";
    ChannelType["IPCMAIN_RESPONSE_FETCH_COLLECTIONS"] = "IPCMAIN_RESPONSE_FETCH_COLLECTIONS";
    ChannelType["IPCMAIN_REQUEST_UPDATE_COLLECTION"] = "IPCMAIN_REQUEST_UPDATE_COLLECTION";
    ChannelType["IPCMAIN_RESPONSE_UPDATE_COLLECTION"] = "IPCMAIN_RESPONSE_UPDATE_COLLECTION";
    ChannelType["IPCMAIN_REQUEST_RESET_ENABLED"] = "IPCMAIN_REQUEST_RESET_ENABLED";
    ChannelType["IPCMAIN_RESPONSE_RESET_ENABLED"] = "IPCMAIN_RESPONSE_RESET_ENABLED";
    // STORE
    ChannelType["IPCMAIN_REQUEST_STORE_FETCH_ALL"] = "IPCMAIN_REQUEST_STORE_FETCH_ALL";
    ChannelType["IPCMAIN_RESPONSE_STORE_FETCH_ALL"] = "IPCMAIN_RESPONSE_STORE_FETCH_ALL";
    ChannelType["IPCMAIN_REQUEST_STORE_FETCH_ROW"] = "IPCMAIN_REQUEST_STORE_FETCH_ROW";
    ChannelType["IPCMAIN_RESPONSE_STORE_FETCH_ROW"] = "IPCMAIN_RESPONSE_STORE_FETCH_ROW";
    ChannelType["IPCMAIN_REQUEST_STORE_UPDATE"] = "IPCMAIN_REQUEST_STORE_UPDATE";
    ChannelType["IPCMAIN_RESPONSE_STORE_UPDATE"] = "IPCMAIN_RESPONSE_STORE_UPDATE";
    ChannelType["IPCMAIN_REQUEST_UPDATE_COUNT"] = "IPCMAIN_REQUEST_UPDATE_COUNT";
    ChannelType["IPCMAIN_RESPONSE_UPDATE_COUNT"] = "IPCMAIN_RESPONSE_UPDATE_COUNT";
    ChannelType["IPCMAIN_REQUEST_UPDATE_COUNTS"] = "IPCMAIN_REQUEST_UPDATE_COUNTS";
    ChannelType["IPCMAIN_RESPONSE_UPDATE_COUNTS"] = "IPCMAIN_RESPONSE_UPDATE_COUNTS";
    ChannelType["IPCMAIN_REQUEST_SYNC_SYSTEM"] = "IPCMAIN_REQUEST_SYNC_SYSTEM";
    ChannelType["IPCMAIN_RESPONSE_SYNC_SYSTEM"] = "IPCMAIN_RESPONSE_SYNC_SYSTEM";
    ChannelType["IPCMAIN_REQUEST_SYNC_ACTIVATED"] = "IPCMAIN_REQUEST_SYNC_ACTIVATED";
    ChannelType["IPCMAIN_RESPONSE_SYNC_ACTIVATED"] = "IPCMAIN_RESPONSE_SYNC_ACTIVATED";
    ChannelType["IPCMAIN_REQUEST_RESET_FAVORITES"] = "IPCMAIN_REQUEST_RESET_FAVORITES";
    ChannelType["IPCMAIN_RESPONSE_RESET_FAVORITES"] = "IPCMAIN_RESPONSE_RESET_FAVORITES";
    ChannelType["IPCMAIN_REQUEST_SYSTEM_STATS"] = "IPCMAIN_REQUEST_SYSTEM_STATS";
    ChannelType["IPCMAIN_RESPONSE_SYSTEM_STATS"] = "IPCMAIN_RESPONSE_SYSTEM_STATS";
    // LOGGER
    ChannelType["IPCMAIN_REQUEST_LOGGER_CREATE"] = "IPCMAIN_REQUEST_LOGGER_CREATE";
    ChannelType["IPCMAIN_RESPONSE_LOGGER_CREATE"] = "IPCMAIN_RESPONSE_LOGGER_CREATE";
    ChannelType["IPCMAIN_REQUEST_LOGGER_DELETE"] = "IPCMAIN_REQUEST_LOGGER_DELETE";
    ChannelType["IPCMAIN_RESPONSE_LOGGER_DELETE"] = "IPCMAIN_RESPONSE_LOGGER_DELETE";
    ChannelType["IPCMAIN_REQUEST_LOGGER_QUERY"] = "IPCMAIN_REQUEST_LOGGER_QUERY";
    ChannelType["IPCMAIN_RESPONSE_LOGGER_QUERY"] = "IPCMAIN_RESPONSE_LOGGER_QUERY";
    ChannelType["IPCMAIN_REQUEST_LOGGER_DELETE_ITEM"] = "IPCMAIN_REQUEST_LOGGER_DELETE_ITEM";
    ChannelType["IPCMAIN_RESPONSE_LOGGER_DELETE_ITEM"] = "IPCMAIN_RESPONSE_LOGGER_DELETE_ITEM";
    ChannelType["IPCMAIN_REQUEST_LOGGER_TRUNCATE"] = "IPCMAIN_REQUEST_LOGGER_TRUNCATE";
    ChannelType["IPCMAIN_RESPONSE_LOGGER_TRUNCATE"] = "IPCMAIN_RESPONSE_LOGGER_TRUNCATE";
})(ChannelType = exports.ChannelType || (exports.ChannelType = {}));
//# sourceMappingURL=ChannelType.js.map